name: tex2nix 
version: 0.1.0
synopsis: create nix expressions for LaTex files
maintainer: Philipp Dargel <chisui@informatik.uni-bremen.de>
license: MIT

ghc-options: -fprint-potential-instances -Wall -O2

dependencies:
- base
- containers
- transformers

library:
  source-dirs: src
  ghc-options: -Werror 
  exposed-modules:
  - Nix.Tex 

executable:
  source-dirs: app 
  main: Main.hs
  dependencies: 
  - tex2nix

tests:
  spec:
    source-dirs: test
    main: Spec.hs 
    dependencies:
    - tex2nix
    - tasty
    - tasty-quickcheck
    - tasty-hunit

